name: 'Matrix Strategy Workflow'

on:
    push:
        branches:
            - main
jobs:
    Build:
        strategy:
            matrix:
                version: [10, 12, 14]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
            - name: Set Up node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.version }}


            

